### ISSUE TITLE
Setting custom difficulties to "Expert" by default

### ISSUE THREAD

**Issue by reealy** [Hiviexd/MVTaikoChecks#10]
initial issue pointed at : https://github.com/Hiviexd/MVTaikoChecks/issues/6#issue-1916524476
I believe this should cover most cases usage without having to manually change the top diff to expert

**Comment by Hiviexd** [comment]
out of scope, aka unfixable with the plugin

however i'm planning to implement proper diffcalc + possibly defaulting to expert in https://github.com/Naxesss/MapsetParser because that's the only viable solution here

**Comment by hongaaronc** [comment]
Yup plan is to implement it fully and properly based on calculated SR.

But if you want something for the short-term (just hardcoded "Expert"), I've posted some instructions on how to hardcode it here for now: https://github.com/Hiviexd/MVTaikoChecks/issues/6#issuecomment-1741318717
