### ISSUE TITLE
check if last note of a map lands on a barline and is snapped 1ms before it

### ISSUE THREAD

**Issue by Hiviexd** [Hiviexd/MVTaikoChecks#11]
uncommon bug but still happens, and when it does, the barline simply doesn't render which isn't supposed to happen, and will result in a pop/dq

it should be a problem check for notes, and a minor check for slider/spinner ends, because this trick tends to be intentionally used for those which is fine lol

additionally it'd be a good idea to add a `TaikoUtils` function that checks if a note is close to a barline by ±10ms, and a function that checks if a note is snapped to a barline, both functions could be quite useful fir this check and in the future

**Comment by hongaaronc** [comment]
do you have a map where this happens? I dont think Ive ever seen it before.

im assuming this isnt the same thing as "detached barlines" where the note/barline have different SV?

**Comment by Hiviexd** [comment]
it resulted in [this pop](https://osu.ppy.sh/beatmapsets/2053402/discussion/-/generalAll#/3927591) (i also posted about this kind of issue a few more times across the years)

.osu diff of the map mentioned above that has the bug: https://nats.are-la.me/8r72MQq.osu
