### ISSUE TITLE
Remove break length BPM scaling from `RestMomentCheck`

### ISSUE THREAD

**Issue by hongaaronc** [Hiviexd/MVTaikoChecks#12]
So going through the code for [RestMomentCheck](https://github.com/Hiviexd/MVTaikoChecks/blob/master/Checks/Compose/RestMomentCheck.cs) again, I realized this is how we are handling BPM scaling for the check:
1. [Scale the minimum gap for what's an acceptable rest moment](https://github.com/Hiviexd/MVTaikoChecks/blob/e12ad5d168cf0a8d65775f4d68894a16bf53222d/Checks/Compose/RestMomentCheck.cs#L145C59-L145C59) (lower BPM => more forgiving)
2. [Scale the amount of continuous mapping w/o break](https://github.com/Hiviexd/MVTaikoChecks/blob/e12ad5d168cf0a8d65775f4d68894a16bf53222d/Checks/Compose/RestMomentCheck.cs#L207) (lower BPM => less forgiving)

I think # 1 makes sense, but do we actually want to be doing # 2?

I feel like often when I'm manually checking for rest moments, I think *not* scaling the amount of continuous mapping, but only scaling the acceptable break gap, makes sense since song structures still follow conventions like 1 bar = 4 measures, which is `16/1`. This seems to be what the RC is built around. I think this is more intuitive so that break structure lines up with song structure.

So I think we should just change [this part](https://github.com/Hiviexd/MVTaikoChecks/blob/e12ad5d168cf0a8d65775f4d68894a16bf53222d/Checks/Compose/RestMomentCheck.cs#L207) to use non-normalized `msPerBeat`, but wanted to confirm this makes sense.

**Comment by Hiviexd** [comment]
from my 3 years of modding i can confidently say that option 1 is the much more common approach (i.e at 125BPM, 1/1 would be a sufficient break for muzus for example), i rarely see option 2 get applied at all

**Comment by hongaaronc** [comment]
wait but right now we're doing both..

so like:
1. 125bpm, 1/1 is a sufficent break
but also...
2. We're saying we need breaks every 32/3 (about 11/1) of continuous mapping

so we dont want 2 right?

**Comment by Hiviexd** [comment]
correct, doesn't make sense to apply 2, especially when we're already applying 1

**Comment by hongaaronc** [comment]
Alright thanks, will update the check then
