### ISSUE TITLE
Unrankable Finishers Check missing some cases?

### ISSUE THREAD

**Issue by hongaaronc** [Hiviexd/MVTaikoChecks#18]
I was looking at this map, when I noticed that there were some unrankable Futsuu finishers that weren't being caught by MV for some reason?

[Unrankable Futsuu Finishers at `00:37:603`](https://nostril.s-ul.eu/Yd1im3BT)

I reviewed the code and not sure why it wouldn't catch this. We should look into it a bit more to debug it.

I'm on a different setup currently so don't have my dev environment but I can check it when I get back. Or if anyone else wants to take a look into it now that'd be cool too.

**Comment by arcs1ne** [comment]
they're 2/3 distance finishers? which are perfectly fine? Lol

**Comment by hongaaronc** [comment]
> they're 2/3 distance finishers?

wait youre right im a dumbass....
