### ISSUE TITLE
refactor/rework the unrankable finishers check

### ISSUE THREAD

**Issue by Hiviexd** [Hiviexd/MVTaikoChecks#5]
current issues:
- very old check and its code is certainly flawed, could really benefit from a revision
- check only works reliably on kantan, futsuu, and muzu difficulties, oni and inner portion really need a rework
- finisher and preceding note same color detection is missing

**Comment by hongaaronc** [comment]
Sounds good, I'm down to work on this.

Whats unrankable for inners+ though? or is that like an old RC thing that's no longer relevant? Looks like in the old code its saying faster than `1/4` is unrankable for inners, but Ive definitely seen ranked inners with `1/6` + finisher, such as this one:
* [wormhole [180 BPM] @ 00:59:956](https://osu.ppy.sh/beatmapsets/1726067)

I can fix up the kantan->oni parts later this week.

**Comment by Hiviexd** [comment]
for inner it should just shoot up "ensure it makes sense" warnings for 1/3 (or higher) finishers at the start and middle of patterns, and whenever the finisher is the same color as its preceding/next note in 1/3 or higher
